# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore      
    - name: LinPub
      run: dotnet publish --configuration Release --runtime linux-x64 --self-contained true --output ./publish
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: linbuild
        path: ./publish
    - name: Tag bs
      uses: KageKirin/git-automatic-semver@v2
      with:
        create_tag: true
        tag_prefix: v
        initial_version: 0.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./publish/linbuild.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
