# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: |  
        cd qse
        dotnet publish --configuration Release --self-contained true --output qse-${{ matrix.os }}-x64
    - name: Tar published files
      run: |
        cd qse
        tar -czf qse-${{ matrix.os }}-x64.tar.gz qse-${{ matrix.os }}-x64
        mv qse-macOS-latest-x64.tar.gz qse-macOS-UNTESTED.tar.gz
        mv qse-windows-latest-x64.tar.gz qse-windows-EXPERIMENTAL.tar.gz
        mv qse-ubuntu-latest-x64.tar.gz qse-linux.tar.gz
        ls
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: qse-${{ matrix.os }}-x64.tar
        path: qse/qse-${{ matrix.os }}-x64.tar
  release:
    needs: build
    runs-on:  ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
    - name: Auto Semver
      uses: oss-actions/auto-semver@v0.1.11
      id: versioning
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        type: patch
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: qse-macOS-UNTESTED.tar
        path: qse-macOS-UNTESTED.tar
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: qse-windows-EXPERIMENTAL.tar
        path: qse-windows-EXPERIMENTAL.tar
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: qse-linux.tar
        path: qse-linux.tar
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.versioning.outputs.version }}
        files: qse-*/qse-*
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
